cask "fd-conduit-term" do
  version "0.0.1"
  sha256 "ee0ab66783bc6a5e90e5605f7799c258f39662d271a9c829dc76d39eda4f5710"

  url "https://github.com/quaggaone/felixdim-font-conduit/archive/refs/tags/v#{version}.tar.gz"
  name "fd-conduit-term"
  desc "Custom build of utility font Iosevka. It's my go-to choice for terminal and code. It lays the conduit between information stored and perceived."
  homepage "https://github.com/quaggaone/felixdim-font-conduit"

  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-Bold.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-BoldItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-ExtraBold.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-ExtraBoldItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-ExtraLight.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-ExtraLightItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-Heavy.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-HeavyItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-Italic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-Light.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-LightItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-Medium.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-MediumItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-Regular.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-SemiBold.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-SemiBoldItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-Thin.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-ThinItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-extd-.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-extd-Bold.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-extd-BoldItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-extd-ExtraBold.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-extd-ExtraBoldItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-extd-ExtraLight.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-extd-ExtraLightItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-extd-Heavy.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-extd-HeavyItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-extd-Italic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-extd-Light.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-extd-LightItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-extd-Medium.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-extd-MediumItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-extd-SemiBold.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-extd-SemiBoldItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-extd-Thin.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term/TTF-Unhinted/fd-conduit-term-extd-ThinItalic.ttf"
end
