cask "fd-conduit-term-nf" do
  version "0.1.0"
  sha256 "ec3dcf7846182be1897fe4b211e1e49bd88aeb739b087369c080d3d34ddcea05"

  url "https://github.com/quaggaone/felixdim-font-conduit/archive/refs/tags/v#{version}.tar.gz"
  name "fd-conduit-term-nf"
  desc "Nerd Font variant of fd-conduit-term"
  homepage "https://github.com/quaggaone/felixdim-font-conduit"

  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-Bold.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-BoldExtended.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-BoldExtendedItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-BoldItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-Extended.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-ExtendedItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-Extrabold.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-ExtraboldExtended.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-ExtraboldExtendedItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-ExtraboldItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-Extralight.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-ExtralightExtended.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-ExtralightExtendedItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-ExtralightItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-Heavy.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-HeavyExtended.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-HeavyExtendedItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-HeavyItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-Italic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-Light.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-LightExtended.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-LightExtendedItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-LightItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-Medium.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-MediumExtended.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-MediumExtendedItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-MediumItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-Regular.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-Semibold.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-SemiboldExtended.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-SemiboldExtendedItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-SemiboldItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-Thin.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-ThinExtended.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-ThinExtendedItalic.ttf"
  font "felixdim-font-conduit-#{version}/dist/fd-conduit-term-nf/fd-conduit-term-nf-ThinItalic.ttf"
end
